support setting reference an memory at run time
mainly so that docker images can run a single command

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,32 +1,7 @@
 #!/bin/bash
 
-echo '
-  | |/ /(_)___ ___  ____ ___  ___  _____
-  |   // / __ `__ \/ __ `__ \/ _ \/ ___/
- /   |/ / / / / / / / / / / /  __/ /    
-/_/|_/_/_/ /_/ /_/_/ /_/ /_/\___/_/     
-'
-
-BASE=`pwd`
-
-if [ ! -e bin/install ];
-then
-    echo "Please run this command from the Ximmer install directory."
-    exit 1
-fi
-
-QUIET=false
-QUIET_FLAG=""
-
-if [ "$1" == -q ];
-then
-    QUIET_FLAG="-q"
-    QUIET=true
-fi
-
 function init_config() {
 
-    CONFIG="eval/pipeline/config.groovy"
     if [ ! -e $CONFIG ];
     then
 
@@ -47,7 +22,7 @@ function init_config() {
     
             done
     
-            echo 'REF="'"$REF"'"' >> $CONFIG
+            echo 'HGFA="'"$REF"'"' >> $CONFIG
         fi
 
         cat eval/pipeline/config.groovy.template >> $CONFIG
@@ -68,9 +43,82 @@ function init_bpipe_config() {
 
 }
 
-init_config
+function set_reference() {
 
-init_bpipe_config
+    if [ ! -e $CONFIG ];
+    then
+           echo
+           echo "ERROR: configuration file config.groovy doesn't exist yet"
+           echo "ERROR: Please run the install script first to set your configuration"
+           exit 1
+    fi
 
-./eval/bpipe install $QUIET_FLAG  ./eval/pipeline/exome_cnv_pipeline.groovy
+        REF="$1"
+
+    if [ -z "$REF" ];
+    then
+           echo
+           echo "ERROR: Please supply a reference argument pointing to the location"
+           echo "ERROR: where your human genome reference will be mapped to inside docker."
+       echo
+           exit 1
+
+    fi
+
+        if [ ! -e $REF ];
+    then
+        echo
+        echo "WARNING: specified reference could not be found. Make sure to map this path when running Ximmer"
+        echo
+    fi
+
+
+        echo 'HGFA="'"$REF"'"' >> $CONFIG
+
+        echo
+        echo "Reference has been set to $REF"
+}
+
+echo '
+  | |/ /(_)___ ___  ____ ___  ___  _____
+  |   // / __ `__ \/ __ `__ \/ _ \/ ___/
+ /   |/ / / / / / / / / / / /  __/ /    
+/_/|_/_/_/ /_/ /_/_/ /_/ /_/\___/_/     
+'
+
+BASE=`pwd`
+
+if [ ! -e bin/install ];
+then
+    cd $(dirname $0)/..
+    BASE=`pwd`
+    echo "Install directory detected as: $BASE"
+fi
+
+QUIET=false
+QUIET_FLAG=""
+
+if [ "$1" == -q ];
+then
+    QUIET_FLAG="-q"
+    QUIET=true
+fi
+
+
+CONFIG="$BASE/eval/pipeline/config.groovy"
+
+
+if [ "$1" == "--set-reference" ];
+then 
+        set_reference $2
+
+else
+    init_config
+
+    init_bpipe_config
+
+    ./eval/bpipe install $QUIET_FLAG  ./eval/pipeline/exome_cnv_pipeline.groovy
+
+fi
+
 
